### ISSUE TITLE
Toast doesn't get automatically dismissed

### ISSUE THREAD

**Issue by fercarcedo** [Maronato/vue-toastification#156] opened 2020-12-28 17:05 UTC
## Versions
- 2.0: starting with 2.0.0-beta.6 all the way to the current release as of writing, 2.0.0-beta.9

## Describe the bug
A toast doesn't get automatically dismissed after the defined timeout, although clicking on the close button works as expected

## Expected behavior
The toast should get automatically dismissed after the defined timeout. On version 2.0.0-beta.5 it works as expected

## Steps to reproduce
1. Configure the library to use a timeout
2. Display a toast
3. Wait for the timeout to expire

```
const toastOptions = {
  position: "bottom-right",
  icon: false,
  timeout: 2000,
  draggabe: false
};

createApp(App).use(Toast, toastOptions);

import { useToast } from 'vue-toastification';
const toast = useToast();
toast("test");
```

## Your Environment
 - OS: Ubuntu 20.04
 - Browser: Firefox 84.0. Also tested on Chrome 86.0.4240.198

**Comment by Maronato** [comment] 2020-12-29 11:11
Hello! Thanks for reporting :)

This seems like a duplicate of #142, #137

This is not an issue with vue-toastification, but with [vue](https://github.com/vuejs/vue-next/issues/2429), to which the solution is described here: https://github.com/vuejs/vue-next/issues/2429#issuecomment-712524999

The tl;dr is that you must upgrade your `vue` and `@vue/compiler-sfc` and make sure that they are **on the same version**.

Below is a CodeSandbox demo showing that toasts are correctly being dismissed with `vue-toastification@2.0.0-beta.9` and `vue@^3.0.0-0`:

[![Edit cold-darkness-ci83x](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cold-darkness-ci83x?fontsize=14&hidenavigation=1&theme=dark)

![CleanShot 2020-12-29 at 07 52 21](https://user-images.githubusercontent.com/19658460/103279482-a5374f00-49ac-11eb-8159-58bc09f593c0.gif)

If you manage to upgrade `vue`, `@vue/compiler-sfc` and still are facing issues, please put together a small reproduction repo/codesandbox so that I can investigate further. For now, I'll close this as it's not reproducible.

**Closed by Maronato** 2020-12-29 11:11 UTC
Labels: Status: Available, Type: Bug

**Comment by fercarcedo** [comment] 2020-12-29 20:17
For some reason I had vue 3.0.0 for both dependencies, but it didn't work. I updated the two dependencies to 3.0.4 and it all works just fine.

Thank you
