### ISSUE TITLE
Toast is not closing in andriod application. 

### ISSUE THREAD

**Issue by svambati** [Maronato/vue-toastification#142] opened 2020-10-29 17:35 UTC
## Versions

- 1.0

## Describe the bug

Toast is not closing automatically even though we have set timeout.

## Expected behavior

Toast has to be closed after certain time.
## Steps to reproduce

Reproduction [demo](link-to-demo).
Steps:
1. Install normally
2. Set up plugin
3. ...

## Your Environment

Andriod Phone - Cromium 33

**Comment by svambati** [comment] 2020-10-29 17:40
I see this is fixed in latest release  in v2. But not sure whether it would be compatible with vue 2

**Comment by Maronato** [comment] 2020-10-29 20:23
Hello @svambati!

Thank you for reporting this, but I'm afraid I've not been able to reproduce the issue.
I'm running Chrome 86 on Android 10 and the [demo](https://maronato.github.io/vue-toastification/) and this [codesandbox](https://codesandbox.io/s/vue-toastification-3btg5?file=/src/main.js) both work fine on it.

The demo is still running v1.x and the codesandbox is running 1.7.8, so maybe the issue lies elsewhere.

Can you provide a way to reproduce your setup so I can help you debug it?

**Comment by cyberco** [comment] 2020-11-08 20:42
I have the same problem in my Vue 3 + TypeScript application. The notification doesn't disappear.

**Comment by Abdulrahmanh95** [comment] 2020-11-10 15:21
So do I, I'm working with Vue 3 JavaScript application and the toast is not closing automatically after timeout exceeds.

**Comment by Abdulrahmanh95** [comment] 2020-11-10 15:35
@svambati @cyberco 
For now, I'm just hacking around in order to make it work using a custom hook (composable):



`export default function useToastr() {`

    function message(type, msg, options) {

        const toast = useToast();
        const toastId = toast[type](msg, options);
        
       setTimeout(() => {
            toast.dismiss(toastId);
        }, options.timeout || 5000);
    }
    function success(msg, options) {
        message('success', msg, options);
    }

    function error(msg, options) {
        message('error', msg, options);
    }

    return {
        error,
        success
    }
}

**Comment by Maronato** [comment] 2020-11-10 15:59
@cyberco @Abdulrahmanh95 which versions are you using (both Vue, Vue-toastification and browser)?

Also, are you able to setup up a minimal repo or codesandbox in which the issue occurs? 

I've not been able to reproduce the issue.

**Comment by Maronato** [comment] 2020-11-10 16:59
Here is a codesandbox showing that the toasts do disappear with Vue **3.0.2** and Vue Toastification **2.0.0-beta.7**:

[![Edit zealous-microservice-63l7k](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zealous-microservice-63l7k?fontsize=14&hidenavigation=1&theme=dark)

![CleanShot 2020-11-10 at 13 45 14](https://user-images.githubusercontent.com/19658460/98704328-49145f00-235b-11eb-95b9-b4a574db7844.gif)


Please keep in mind that, because of a [recent vue commit](https://github.com/vuejs/vue-next/commit/62f26173ba715fd8bf2b131e19d94275106e830d), there are some issues regarding [mismatched versions of vue and its compiler](https://github.com/vuejs/vue-next/issues/2429#issuecomment-712524999) that lead to [kebab-case events not firing correctly](https://github.com/vuejs/vue-next/issues/2429)(also [here](https://github.com/vuejs/vue-next/issues/2480), [here](https://github.com/vuejs/vue-next/issues/2526) and [here](https://github.com/vuejs/vue-next/issues/2525)). Incidentaly, there has been a recent [issue filled here on Vue Toastification](https://github.com/Maronato/vue-toastification/issues/137) that reported the same issue and, since then, only [vue >=3.0.2](https://github.com/Maronato/vue-toastification/blob/0591a70fe5af0dedb19b7c26bde88981e4e342c9/package.json#L89) is supported.

Make sure that your Vue installation is up to date and report back if the issue persists. Take a look inside your `package-lock` and make sure that both `vue` and `@vue/compiler-sfc` are on `^3.0.2`.

**Comment by svambati** [comment] 2020-11-18 21:07
> @svambati @cyberco
> For now, I'm just hacking around in order to make it work using a custom hook (composable):
> 
> `export default function useToastr() {`
> 
> ```
> function message(type, msg, options) {
> 
>     const toast = useToast();
>     const toastId = toast[type](msg, options);
>     
>    setTimeout(() => {
>         toast.dismiss(toastId);
>     }, options.timeout || 5000);
> }
> function success(msg, options) {
>     message('success', msg, options);
> }
> 
> function error(msg, options) {
>     message('error', msg, options);
> }
> 
> return {
>     error,
>     success
> }
> ```
> 
> }

**Comment by Maronato** [comment] 2020-12-03 15:05
Closing this since no reproduction steps have been provided and it really seems like a duplicate of #137

**Closed by Maronato** 2020-12-03 15:05 UTC
Labels: Status: Available, Type: Bug, need more info
