### ISSUE TITLE
vue-toastification 2.0 - the progress bar finished but notification isn't getting closed

### ISSUE THREAD

**Issue by galbarnissan** [Maronato/vue-toastification#157] opened 2020-12-30 09:32 UTC
## Versions

- 2.0

## Describe the bug

When using the progress bar, the toast isn't closed when the progress bar finished and remains indefinitely. 

## Expected behavior

When using the progress bar then when the progress bar finishes the toast should be automatically closed. 

## Steps to reproduce
Check sandbox:
https://codesandbox.io/s/intelligent-sun-ib6b3?file=/src/App.vue

https://user-images.githubusercontent.com/5380178/103342564-7b585800-4a92-11eb-9da0-063f6e68db95.mov

**Comment by Maronato** [comment] 2021-01-03 00:28
Hello!
This is a duplicate of #156, #142, #137

Update your `vue` and `@vue/compiler-sfc` to `^3.0.4` and it [will work](https://github.com/Maronato/vue-toastification/issues/156#issuecomment-752227680).

**Closed by Maronato** 2021-01-03 00:28 UTC
Labels: Status: Available, Type: Bug
