### ISSUE TITLE
Toasts are not shown when calling outside of the component

### ISSUE THREAD

**Issue by koljada** [Maronato/vue-toastification#146] opened 2020-11-16 11:56 UTC
## Versions
- 2.0

## Describe the bug
Toasts are not shown when calling outside of the component

## Expected behavior
Toasts are shown always

## Steps to reproduce
Reproduction [demo](https://codesandbox.io/s/frosty-minsky-0v79i?file=/src/components/HelloWorld.vue).
Steps:
1. Create a helper which uses the library
2. Call this helper in the component
3. Observe that a toast is not shown

## Your Environment
Not relevant

## Additional context
With composition API approach it's typical to create reusable functions and I think it's totally fine to call toast library from such function. I believe that with vue3 reactivity system it's no longer needed to use event bus, I think it might be enough to create a singleton instance with internal reactive store for toast events

**Comment by Maronato** [comment] 2020-11-17 05:23
Hello!

Your example does not work because `useToast` uses dependency injection to retrieve the closes instance in the component tree. Since the `setTimeout` callback is executed by the event loop, it does not have access to the vue instance.

A direct solution to your issue is just to call `useToast` outside of the callback:

```ts
export const useTimeout = (duration) => {
  const toast = useToast();
  const timer = setTimeout(() => {
    console.warn("time is out");
    toast.warning("Time is out");
  }, duration * 1000);
   return () => clearTimeout(timer);
};
```

The solution above, however, does not answer the underlying issue of `useToast` not working as might be expected.

Vue Toastification was designed to be extensible and not make assumptions about how it would be used. This means that it may be initialized multiple times in the component tree, it may be used inside web components, and it may even be used by react apps. The tradeoff here is that sometimes for more complex usages you will need to manually assign and manage `EventBus` instances.

90% of the time the plugin will handle it for you using Vue's dependency injection but the other 10% (e.g. When calling it from outside the `setup()` context) require something like the solution described in the comment linked below:

https://github.com/Maronato/vue-toastification/issues/134#issuecomment-705120669

I'll close the issue, but I'm open to discuss pros and cons of alternative designs to Vue Toastification if you wish.

**Closed by Maronato** 2020-11-17 05:23 UTC
Labels: Status: Available, Type: Bug

**Comment by makurtu** [comment] 2020-11-26 08:56
Hi @Maronato!

I have same issue using vue-tostification outside of component. I'm using a file to export `axios` globally on my project (because I use JWT authentication). I wish to use `toast` on axios' interceptors, but toasts aren't shown.

An example of my implementation:

```js
import axios from "axios";
import { useToast } from "vue-toastification";

const toast = useToast();

const instance = axios.create({
  baseURL: process.env.VUE_APP_API_URL
});

instance.interceptors.response.use(
  function(response) {
    return response;
  },
  function(error) {
    if (400 === error.response.status) {
      toast.error("Intercept!");
      return Promise.reject(error);
    } else {
      return Promise.reject(error);
    }
  }
);

export default instance;
```

It works as expected if I use a native `alert()` on interceptor, but if I put a `toast.error`, it doesn't work.

**Comment by Maronato** [comment] 2020-11-26 15:07
Hello @makurtu !

Please see: https://github.com/Maronato/vue-toastification/issues/134#issuecomment-705120669

You'll need to use the `useGlobalToast` method mentioned in the comment.

**Comment by makurtu** [comment] 2020-11-27 09:44
Hi @Maronato !

I tried to use your code, but no luck. Here is my implementation:

```js
import axios from "axios";
import { createToastInterface, EventBus } from "vue-toastification";

// This will be the global event bus
const globalEventBus = new EventBus();

const globalToast = createToastInterface(globalEventBus);

const instance = axios.create({
  baseURL: process.env.VUE_APP_API_URL
});

instance.interceptors.response.use(
  function (response) {
    return response;
  },
  function (error) {
    if (400 === error.response.status) {
      console.log("Intercept!");
      globalToast.error("Intercept!");
      return Promise.reject(error);
    } else {
      return Promise.reject(error);
    }
  }
);

export default instance;
```
I put all code in same file and removed unused functions.

**Comment by Maronato** [comment] 2020-11-27 14:21
Vue Toastification works by creating a separate component tree wherein the actual toast components will be dynamically shown. To communicate with this separate component tree, your application needs a common interface that can tell it to show your toasts. 

That is where the `EventBus` comes in. It is an object that is shared between your `useToast` calls and the separate component tree, and it's used to send the events of toast creation, dismissal, etc.

When you install Vue Toastification as a plugin:
```js
import Toast from 'vue-toastification'

app.use(Toast)
```

It creates an `EventBus` behind the scenes and uses Vue's [dependency injection](https://v3.vuejs.org/guide/component-provide-inject.html) to make that `EventBus` available to subsequent `useToast` calls.

The issue you, as well as this issue and #134 were facing is that Vue's dependency injection assumes you are using it from within Vue's component tree. Axios, however, is not, so you need another way to initialize the plugin so that you can communicate with the component tree from outside Vue's component tree.

To do that, you need to manually create the `EventBus`, then create the separate component tree that uses the event bus and finally create an interface to that separate component tree.

Therefore your final solution should be something like the following:

```js
// toast.js
import {
  createToastInterface,
  EventBus,
  toastInjectionKey
} from 'vue-toastification';

// This will be the global event bus
const globalEventBus = new EventBus();

// Returns an interface to the global toast component tree
export function useGlobalToast() {
  return createToastInterface(globalEventBus);
}

// Use this as a plugin to register instance and injected toasts
export function provideGlobalToast(app, options) {
  // Create the separate component tree
  const toast = createToastInterface({ ...options, eventBus: globalEventBus });

  // Provide using Vue dependency injection
  app.provide(toastInjectionKey, toast);
}
```

```js
// main.js
import { createApp } from 'vue';
import { provideGlobalToast } from './toast';
// ...

app.use(provideGlobalToast)
```

```js
// axios.js
import axios from "axios";
import { useGlobalToast } from "./toast";

const globalToast = useGlobalToast();

const instance = axios.create({
  baseURL: process.env.VUE_APP_API_URL
});

instance.interceptors.response.use(
  function (response) {
    return response;
  },
  function (error) {
    if (400 === error.response.status) {
      console.log("Intercept!");
      globalToast.error("Intercept!");
      return Promise.reject(error);
    } else {
      return Promise.reject(error);
    }
  }
);

export default instance;
```

**Comment by Maronato** [comment] 2020-11-27 15:47
Good news @makurtu!

With the new version [`2.0.0-beta.8`](https://www.npmjs.com/package/vue-toastification/v/2.0.0-beta.8) you won't need all of that code to make your setup work. Toasts are now global by default so all you need to do is:

1. Install the plugin as usual
```js
import { createApp } from "vue";
import Toast from "vue-toastification";
import "vue-toastification/dist/index.css";

// ...
 
app.use(Toast);
```

2. And then call `useToast`:
```js
import axios from "axios";
import { useToast } from "vue-toastification";

const toast = useToast();

const instance = axios.create({
  baseURL: process.env.VUE_APP_API_URL
});

instance.interceptors.response.use(
  function(response) {
    return response;
  },
  function(error) {
    if (400 === error.response.status) {
      toast.error("Intercept!");
      return Promise.reject(error);
    } else {
      return Promise.reject(error);
    }
  }
);

export default instance;
```

**Comment by makurtu** [comment] 2020-11-30 07:54
Hi @Maronato !

Many many thanks to take your time on explaining me some Vue Internals tips!

I've updated my `vue-tostification` and now it works as expected!! :tada: 

Again, many thanks @Maronato
